@startuml entity

entity Category {
    id: int <<PK>>
    name: str
}

entity Subcategory {
    id: int <<PK>>
    name: str
    category: Category <<FK>>
}

entity Buy {
    id: int <<PK>>
    date: Date
    category: Category <<FK>>
    subcategory: Subcategory <<FK>>
}


Category ||-o{ Subcategory
Buy ||-down-o{ Category
Buy ||-down-o{ Subcategory

@enduml