@startuml component

package Common {
    component [common.Data]
    component [Date]
}

package Domain {
    component [Models]
    component [domain.Data]
}

component [Web UI]
component [Main]


[Main] -down-> [domain.Data]
[Main] -down-> [Models]
[domain.Data] -right-> [Models]
[domain.Data] -down-> [common.Data]
[common.Data] -> [Date]

@enduml