@startuml usecase

actor User

User -down-> (Save&load data)
User -down-> (CRUD)
(CRUD) <-down. (Category) : extends
(CRUD) <-down. (Subcategory) : extends
(CRUD) <-down. (Buy) : extends

User -down-> (Import)
(Import) <.-down- (Buys) : extends

@enduml