version: "3.7"

services:
  finance_plan_postgres:
    image: postgres:alpine
    env_file:
      - backend/src/docker.env
    ports:
      - "5432:5432"

  finance_plan_redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  finance_plan:
    depends_on:
      - finance_plan_postgres
      - finance_plan_redis
    links:
      - finance_plan_postgres
      - finance_plan_redis
    ports:
      - "80:8080"
    environment:
      - POSTGRES_HOST=finance_plan_postgres
    build: backend/src
