# Test your FastAPI endpoints

GET http://127.0.0.1:8080/docs
Accept: application/json
###

POST http://127.0.0.1:8080/create_category
Content-Type: application/json

{
  "name": "string"
}
###

POST http://127.0.0.1:8080/save
###

POST http://127.0.0.1:8080/load
###

GET http://127.0.0.1:8080/categories
Accept: application/json
###

PUT http://127.0.0.1:8080/update_category?id_=0
Content-Type: application/json

{
  "name": "string"
}
###

DELETE http://127.0.0.1:8080/delete_category?id_=0
###

POST http://127.0.0.1:8080/create_subcategory
Content-Type: application/json

{
  "name": "string"
}
###
GET http://127.0.0.1:8080/subcategories
Accept: application/json
###

PUT http://127.0.0.1:8080/update_subcategory?id_=0
Content-Type: application/json

{
  "name": "string"
}
###

DELETE http://127.0.0.1:8080/delete_category?id_=0
###
